name: Bug Report
description: Report a bug or unexpected behavior in JPlag
title: "[Bug]"
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ### Bug Description

        Please provide a clear and concise description of the problem you're experiencing with JPlag.

  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description
      placeholder: Describe the issue in detail, including where it occurs (CLI, API, etc.)...
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Run '...'
        3. Observe '...'
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      placeholder: Describe what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      placeholder: Describe what actually happened, including any error messages...
    validations:
      required: true

  - type: input
    id: environment_os
    attributes:
      label: Operating System
      placeholder: E.g., Windows 11, macOS 13.4, Ubuntu 22.04
    validations:
      required: false

  - type: input
    id: environment_java
    attributes:
      label: Java Version
      placeholder: E.g., OpenJDK 17, Oracle JDK 21
    validations:
      required: false

  - type: input
    id: jplag_version
    attributes:
      label: JPlag Version
      placeholder: E.g., 6.1.0
    validations:
      required: true

  - type: textarea
    id: logs_or_screenshots
    attributes:
      label: Logs or Screenshots
      description: If applicable, add logs or screenshots to help explain the issue.
      placeholder: Paste logs here or drag & drop screenshots...
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem, such as configuration files or related issues.
      placeholder: Anything else we should know?
    validations:
      required: false
