name: Question or Discussion
description: Ask a question or start a discussion about JPlag
title: "[Question] "
labels: ["question"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ### Question or Discussion

        Thanks for reaching out! Please provide details about your question or the topic you'd like to discuss.

  - type: textarea
    id: question_or_discussion
    attributes:
      label: Question or Discussion
      description: A clear and concise explanation of your question or discussion topic.
      placeholder: E.g., how does JPlag handle minor code formatting differences?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Include any relevant context, such as how you're using JPlag (CLI, Web, API) or the programming language in question.
      placeholder: E.g., I'm comparing Python assignments using the CLI and noticed differences in results...
    validations:
      required: false

  - type: textarea
    id: additional_details
    attributes:
      label: Additional Details
      description: Add any other details, examples, screenshots, or links that could help clarify your topic.
      placeholder: Optional but helpful - feel free to elaborate.
    validations:
      required: false
